OverlayCard component
flatiron-labs/design-system pull request #46
Opened 2021-03-03 22:20 UTC by ann-schulte-flatironschool

**Additions:**

- OverlayCard Component

2021-03-03 22:50 UTC, tmilewski requested changes
Left a few comments. Is there a better name for this? I was very confused as to what it was until I dug in.

2021-03-03 22:50 UTC, tmilewski commented on src/components/OverlayCard/OverlayCard.tsx
> +      {backgroundStyle === 'red' && (
Any reason we're using red for pink, turq for blue? We can roll these up into one call if we consolidate the naming?

2021-03-03 22:50 UTC, tmilewski commented on src/components/OverlayCard/OverlayCard.tsx
> +      )}{' '}
Why the added space here?

2021-03-03 22:50 UTC, tmilewski commented on src/components/Icon/Icon.d.ts
> +  children?: React.ReactNode
I'd suggest using the SVG as a background or having the text as an absolute element on top.

All of this said, I'd also suggest not including the assets here and making them available for use elsewhere. Then place them in via a prop.

By putting them here, they get bundled with everything and slow things down (see: loading gif).

Using a prop, the consumer can define what's used and how they're loaded (bundled/external assets/etc.)

2021-03-03 22:50 UTC, tmilewski commented on src/components/OverlayCard/OverlayCard.tsx
> +      {backgroundStyle === 'red' && (
That said, see my original comment about using props.

2021-03-03 23:08 UTC, ann-schulte-flatironschool commented on src/components/OverlayCard/OverlayCard.tsx
> +      )}{' '}
accident

2021-03-04 17:22 UTC, tmilewski approved these changes

2021-03-04 17:50 UTC, merged